### ISSUE TITLE
tag a version

### ISSUE THREAD

**Issue by glensc** [pjparra/assetic-smarty#5]
i'd like to use this package via composer, but without `dev-master`. 

so could you please:
1. add license to package.json (packagist.org shows Unknown License)
2. tag the release (git tag and push to github)

could you also add to readme smarty version supported or at least version that you initially tested. i.e is this for smarty2 or smarty3?

**Comment by pjparra** [comment]
Hi,
It will work with smarty3, I will add it to the readme.
I will also look into adding tags & license to the project, as soon as I can. 

Otherwise, you could fork, do these changes and do a pull request, I will gladly accept it. :smile:

**Comment by glensc** [comment]
i'm interested on git tag mostly, the other's are worth to have, but irrelevant

tagging is simple as:
```
git fetch origin
git tag 1.0 origin/master
git push origin 1.0
```

**Comment by pjparra** [comment]
Sure, I understand. I would hesitate using dev-master too!
I just pushed the 1.0 tag.

**Comment by pjparra** [comment]
Sure, I understand. I would certainly hesitate to use an untagged project too!
I just pushed two commits and the 1.0 tag.

**Comment by glensc** [comment]
1.0 tag not present in packagist:
https://packagist.org/packages/pjparra/assetic-smarty

could you recheck, resync, whatever.

another guess is that it does not like 1.0 tag, wants 1.0.0, or so.

**Comment by pjparra** [comment]
Unfortunately, I do not own the packagist "repository". So I can't do
anything directly.
I'll try to replace the tag with 1.0.0

**Comment by glensc** [comment]
what do you mean you do not own? it's under your github namespace:
https://packagist.org/packages/pjparra/assetic-smarty -> https://github.com/pjparra/assetic-smarty

what i recall, was to go to packagist.org, log in using github, and then some buttons appear and probably a way to re-setup the hook.

**Comment by pjparra** [comment]
Until a few hours ago, I didn't even have a packagist account.
It was probably set up by the guy who made the pull request to include a
composer.json file in the first place. Also, the picture displayed on
packagist is certainly not mine.
I'll try to contact him to see if he is willing to transfer ownership.

**Comment by glensc** [comment]
the screenshot is from package i own. shows example which buttons will appear.

ok, did not know one can register mismatching names github vs packagist.
